name: Todo Deployment
on:
  push:
    branches: [ main ]
jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd test-todo
            git pull origin 
            docker-compose down
            docker-compose up 
